steps:
  - name: 'python'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  - name: 'python'
    entrypoint: 'pytest'
    args: ['test_main.py']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-flask-app-staging', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-flask-app-staging']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'my-flask-app-staging'
      - '--image=gcr.io/$PROJECT_ID/my-flask-app-staging'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--update-secrets'
      - 'API_KEY=my-api-key:latest'
